---

- name: get NetApp-specific facts
  hosts: testing_host
  connection: local

  tasks:
    - name: Get facts from netapp-setup module
      netapp-setup: 
        host={{ inventory_hostname }}
        nauser=admin
        napass=netapp123
        logfile=/tmp/ansible-netapp.log
    - name: check a fact
      debug: msg="system-name = {{ system_node_info[item.key]['system-info']['system-name'] }}" 
      with_dict: "{{ system_node_info }}"